#This compose file is for setting up a docker container for a postgresql database as the windows version 
#is not very compatible with my WSL environment
services:

  db:
    image: postgres:alpine
    container_name: todo_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/backup/data
volumes:
  todo_data: